import Script from "next/script"
import { ResolvingMetadata, Metadata } from "next"
import { HydrationBoundary, dehydrate } from "@tanstack/react-query"
import { usePostQuery, PostQuery } from "../../../../generated/graphq"
import getQueryClient from "@/utils/getQueryClient"
import { getAutogeneratedPostOG } from "@/utils/social/og"
import "../../../utils/highlightjs.css"

const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST as string

interface SlugLayoutProps {
    children: React.ReactNode,
    params: {
        slug: string
    }
}

interface Props {
    params: {
      slug: string;
    };
  }
  
  export async function generateMetadata(
    props: Props,
    parent: ResolvingMetadata
  ): Promise<Metadata> {
    const queryClient = getQueryClient();
  
    await queryClient.prefetchQuery({
      queryKey: usePostQuery.getKey({
        host,
        slug: props.params.slug,
      }),
      queryFn: usePostQuery.fetcher({
        host,
        slug: props.params.slug,
      }),
    });
    const data = queryClient.getQueryData<PostQuery>(
      usePostQuery.getKey({
        host,
        slug: props.params.slug,
      })
    );
    const post = data?.publication?.post!;
    return {
      title: post.seo?.title || post.title,
      description: post.seo?.description || post.subtitle || post.brief,
      twitter: {
        card: "summary_large_image",
        title: post.seo?.title || post.title,
        description: post.seo?.description || post.subtitle || post.brief,
        images: [
          {
            url:
              post.ogMetaData?.image ||
              post.coverImage?.url ||
              getAutogeneratedPostOG(post, data?.publication!),
            width: 1200,
            height: 630,
          },
        ],
      },
      openGraph: {
        title: post.seo?.title || post.title,
        url: post.url,
        description: post.seo?.description || post.subtitle || post.brief,
        images: [
          {
            url:
              post.ogMetaData?.image ||
              post.coverImage?.url ||
              getAutogeneratedPostOG(post, data?.publication!),
            width: 1200,
            height: 630,
          },
        ],
      },
    };
  }


export default async function SlugLayout({ children, params }: SlugLayoutProps) {
    const queryClient = getQueryClient()

    await queryClient.prefetchQuery({
        queryKey: usePostQuery.getKey({
            host,
            slug: params.slug
        }),
        queryFn: usePostQuery.fetcher({
            host,
            slug: params.slug
        })
    })

    return (
        <>
            <HydrationBoundary state={dehydrate(queryClient)}>
                {children}
            </HydrationBoundary>
            <Script src="../../../utils/highlight.js"/>
        </>
    )
}